const CHECKOUT_URL="https://syncpaycheckout.com/checkout/a2ec33d1-d4c0-44a7-8066-72036256505e+a2ec3366-0a47-4a13-8247-5f417a926c75";
const TL=[["2003","Primeiro governo Lula","Lula toma posse em 1º de janeiro de 2003.","Planalto"],
["2010","Fim do segundo mandato","O segundo mandato termina em 31/12/2010.","Planalto"],
["2018","Prisão e consequências jurídicas","Condenado em primeira instância em 2017 e em segunda em janeiro de 2018, no caso do tríplex, Lula foi preso em abril de 2018.","STF / TRF-4"],
["2019","Decisões judiciais posteriores","Em novembro de 2019, o STF encerrou a execução da pena após condenação em segunda instância e Lula foi solto.","STF"],
["2021","Anulação das condenações","Em março de 2021, o STF anulou as condenações da Justiça Federal de Curitiba por incompetência do foro e reconheceu a parcialidade do juiz no caso do tríplex. O mérito não foi julgado.","STF"],
["2023","Retorno à Presidência","Lula vence a eleição de 2022 e toma posse em 1º de janeiro de 2023.","TSE"],
["2026","Situação atual","O governo está no terceiro mandato. Os dados fiscais e econômicos mais recentes estão nas seções abaixo, com data.","Tesouro / Fazenda"]];
document.getElementById('tlc').innerHTML=TL.map(x=>`<details class="rv"><summary><b>${x[0]}</b><span>${x[1]}</span></summary><div class="dd">${x[2]}<small>Fonte: ${x[3]}</small></div></details>`).join('');
const CS=[["Caso do tríplex do Guarujá",["Condenação","Anulação"],"Apuração sobre suposto benefício de uma empreiteira em um apartamento no Guarujá (SP).","Segundo o MPF, o imóvel seria vantagem indevida ligada a contratos da Petrobras.","Lula negou ser dono do imóvel e alegou perseguição.","Condenado em 2017 (1ª instância) e confirmado em 2ª instância em 2018. Em 2021, o STF anulou por incompetência do foro e reconheceu a parcialidade do juiz.","Condenação anulada. Mérito não julgado."],
["Caso do sítio de Atibaia",["Condenação","Anulação"],"Apuração sobre reformas em um sítio em Atibaia (SP) por empreiteiras.","Segundo o MPF, as obras seriam vantagem indevida.","Lula negou ser dono do sítio e alegou perseguição.","Condenado em primeira instância em 2019. As condenações da Justiça de Curitiba foram anuladas pelo STF em 2021 por incompetência do foro.","Condenação anulada. Mérito não julgado."]];
document.getElementById('cases').innerHTML=CS.map(c=>`<article class="case rv"><h3>${c[0]}</h3>${c[1].map((s,i)=>`<span class="stat ${i?'y':''}">${s}</span>`).join('')}<dl><dt>O que foi investigado</dt><dd>${c[2]}</dd><dt>Qual foi a acusação</dt><dd>${c[3]}</dd><dt>O que a defesa disse</dt><dd>${c[4]}</dd><dt>O que a Justiça decidiu</dt><dd>${c[5]}</dd><dt>Status atual</dt><dd>${c[6]}</dd></dl><small class="src">Fonte: STF, TRF-4. Conferir nos autos.</small></article>`).join('');
const RK=[["01","Contas públicas","Governo Central: déficit primário de R$ 48,2 bi em junho/2026 e de R$ 144,1 bi (1,08% do PIB) em 12 meses.","O resultado está abaixo da meta fiscal do ano (superávit de 0,25% do PIB, com tolerância de 0,25 p.p.).","O Tesouro atribui o déficit do semestre ao pagamento de precatórios em março e destaca a arrecadação de junho, a maior para o mês desde 2000.","Receita líquida de R$ 195,2 bi em junho (+10,3% real); despesas +9% reais.","Tesouro Nacional, 30/07/2026"],
["03","Inflação","A Fazenda elevou a projeção do IPCA 2026 de 4,5% (mai) para 5,1% (jul) e reduziu para 4,9% (set).","Críticos apontam projeção acima do teto da meta, de 4,5%.","A SPE cita alimentos e o conflito no Oriente Médio e vê a Selic em patamar contracionista.","IPCA projetado: 5,1% em 15/07; 4,9% em 22/09/2026. Meta: teto de 4,5%.","Boletim Macrofiscal, SPE/Fazenda"],
["06","Investimentos","Investimentos federais somaram R$ 49,8 bi de janeiro a junho de 2026.","Crítica a documentar com fonte.","Governo destaca a alta de investimentos.","Alta real de 65,7% sobre o primeiro semestre de 2025.","Tesouro Nacional, jun/2026"],
["PIB","Crescimento","A Fazenda reduziu a projeção do PIB 2026 de 2,3% (jul) para 2,0% (set).","Críticos apontam desaceleração da atividade.","A Fazenda cita o desempenho de serviços, o endividamento das famílias e os efeitos defasados da queda de juros.","PIB projetado: 2,3% em 15/07; 2,0% em 22/09/2026.","Boletim Macrofiscal, SPE/Fazenda"]];
const PD=[["02","Dívida pública","Tesouro Nacional / Banco Central"],["04","Gastos governamentais","Tesouro Nacional / SIOP"],["05","Impostos","Receita Federal"],["07","Estatais","Ministério da Gestão / SEST"],["08","Políticas sociais","Ministério do Desenvolvimento Social / IBGE"]];
document.getElementById('risks').innerHTML=RK.map(r=>`<article class="risk rv"><div class="n">${r[0]}</div><h3>${r[1]}</h3><dl><dt>O que o governo fez</dt><dd>${r[2]}</dd><dt>Qual é a crítica</dt><dd>${r[3]}</dd><dt>Argumento do governo</dt><dd>${r[4]}</dd><dt>O que os dados mostram</dt><dd>${r[5]}</dd></dl><small class="src">Fonte: ${r[6]}</small></article>`).join('')+PD.map(r=>`<article class="risk p rv"><div class="n">${r[0]}</div><h3>${r[1]}</h3><p class="dd" style="padding:0">Dado e fonte a inserir antes da publicação. Fonte sugerida: ${r[2]}.</p></article>`).join('');
const FL=[["Ministério da Fazenda: déficit primário em junho/2026","https://www.gov.br/fazenda/pt-br/assuntos/noticias/2026/julho/deficit-primario-do-governo-central-em-junho-soma-r-48-2-bilhoes/"],["Agência Gov: Boletim Macrofiscal de julho","https://agenciagov.ebc.com.br/noticias/202607/boletim-macrofiscal-de-julho-de-2026-mantem-a-projecao-de-crescimento-de-2-3-para-o-ano"],["Boletim Macrofiscal de setembro (B3/Agência Brasil)","https://borainvestir.b3.com.br/noticias/governo-reduz-projecao-do-pib-para-2-em-2026-e-23-em-2027/"],["Relatório do Tesouro, jun/2026 (Poder360)","https://static.poder360.com.br/uploads/2026/07/boletim_jun26.pdf"],["Agência Estado: déficit de R$ 48,178 bi","https://www.dgabc.com.br/Noticia/4338337/governo-central-tem-deficit-primario-de-r-48-178-bilhoes-em-junho-afirma-tesouro"],["STF","https://www.stf.jus.br"],["TSE","https://www.tse.jus.br"],["Planalto","https://www.planalto.gov.br"]];
document.getElementById('fl').innerHTML=FL.map(x=>`<li style="padding:.8rem 0;border-bottom:1px solid var(--bd)"><a href="${x[1]}" rel="noopener">${x[0]}</a></li>`).join('');
document.querySelectorAll('[data-cta]').forEach(a=>a.href=CHECKOUT_URL);
document.getElementById('obb').onclick=()=>document.getElementById('ob').classList.toggle('on');
const io=new IntersectionObserver(e=>e.forEach(x=>{if(x.isIntersecting){x.target.classList.add('in');x.target.querySelectorAll('i[data-v]').forEach(i=>{const m=+i.closest('.bars').dataset.max;i.style.width=(i.dataset.v/m*100)+'%'});io.unobserve(x.target)}}),{threshold:.15});
document.querySelectorAll('.rv,.line').forEach(e=>io.observe(e));
const bar=document.getElementById('bar'),fc=document.getElementById('fcta'),hi=document.getElementById('hi'),fin=document.getElementById('final');
function p(){const m=document.documentElement.scrollHeight-innerHeight,r=scrollY/m;bar.style.transform='scaleX('+r+')';fc.classList.toggle('on',r>.25&&fin.getBoundingClientRect().top>innerHeight*.9);if(!matchMedia('(prefers-reduced-motion:reduce)').matches&&scrollY<innerHeight)hi.style.transform='translateY('+scrollY*.05+'px)'}
addEventListener('scroll',p,{passive:true});p();